### ISSUE TITLE
在 linux 下试用了下，读取 xl/sharedstrings.xml 文件的文件名问题

### ISSUE THREAD

**Issue by hanxi** [cloudwu/luaxlsx#1]
我在 linux 解压 xlsx 文件发现 `xl/sharedstrings.xml` 文件应该为 `xl/sharedStrings.xml`

**Comment by cloudwu** [comment]
可是在 luazip 封装库里使用的是大小写无关模式的啊。

**Comment by cloudwu** [comment]
我知道了，这里应该传 2
https://github.com/cloudwu/luaxlsx/blob/master/luaclib/minizip/unzip.c#L384

**Comment by hanxi** [comment]
goodjob.
